### ISSUE TITLE
new fixes from other branches

### ISSUE THREAD

**Issue by thenewguy** [datahub/grappelli-nested-inlines#1]
Not sure how they apply to this package, but https://github.com/silverfix/django-nested-inlines has some fixes mentioned in https://code.djangoproject.com/ticket/9025

**Comment by allanjamesvestal** [comment]
Thanks! I've identified and ~~am working to incorporate~~ have incorporated the following commits:
- ~~['Update admin.py - fix errors "cannot import name force_unicode", "...forms, helpers"'](https://github.com/silverfix/django-nested-inlines/commit/74b6afc387f321c211cfcebc14488e1e6857d08d)~~ _Fixed with e823040664f4e2bd92380181e872f3da17e29cd0._
- ~~['Fixed a bug that would be skip any custom validation in clean() method'](https://github.com/silverfix/django-nested-inlines/commit/5cf8d368638927f4e12de965b73d08f51b77fbef)~~ _Fixed with aa2bc25b95159f37ef6f0f5c48cdd2b840871dfd._
- ~~['Update admin.py - forgotten parameter'](https://github.com/silverfix/django-nested-inlines/commit/d4e90b4ffac8086a0c3fc4f5fe046c88ecd4f88f)~~ _Fixed with 0ec2581cc6d733b125e0a0618afb6895d0f50ea3._
- ~~['Fixed MultiValueDictKeyError in django-1.6'](https://github.com/silverfix/django-nested-inlines/commit/457c47405b38496362c74a98a30bc4befe6b711a)~~ _Fixed with a307ee06c3b4b106ce55efc870611bc79d85fc74._
- ~~['Add back-compatibility on has_auto_field -> needs_explicit_pk_field fix'](https://github.com/silverfix/django-nested-inlines/commit/49bc27a4d32c27b23efca13579ad07f561851e11)~~ _Fixed with 031f871502a2c347060b43dbb04e12fab80d5efe._
- ~~['Fix ValueError('self.form must to be an instance of BaseNestedModelForm') for ModelAdmin without form attr.'](https://github.com/silverfix/django-nested-inlines/commit/59481d903096630c02f8e49dc1d588f1c6731218)~~ _Fixed with 5d63f04394a2a6826a425a7532924b328909d17b._
- ~~['Add package_data to be able to use python ./setup.py install instead of git target'](https://github.com/silverfix/django-nested-inlines/commit/8bd86a7f40276584594fb19e4bd8023095299a6a)~~ _Fixed with bd9e44485cb25b1c0698c6b70125b0f4a90ee846._
- ~~['Fix save_as_new'](https://github.com/silverfix/django-nested-inlines/commit/78edd4b732d7ec9dbe52d25f5d417624931d5b57)~~ _Fixed with 14e34b11a09b9bf3774f1b4a0d54973145bb93ec._

I'd seen this additional commit, but probably won't incorporate it as this library's javascript is significantly different from silverfix or Soaa-'s:
- ['Nested formsets bug fixes'](https://github.com/silverfix/django-nested-inlines/commit/b1a34227febe2329cd8a0294deb72967d87d247f)

I know it's been awhile since you filed this issue, but if you still use this library I'd appreciate others' feedback on whether these are all the relevant changes. Appreciate being linked to the updated library.

**Comment by allanjamesvestal** [comment]
I've incorporated each of the 8 Silverfix commits mentioned above. Leaving this open for now in case anyone notices more fixes from elsewhere that I should roll in.
