### ISSUE TITLE
Cannot create new nested lines after initial load

### ISSUE THREAD

**Issue by RonnieHemmingsen** [datahub/grappelli-nested-inlines#17]
Hi lovely creator(s) of this plugin.
First of all: Thank you, it is really helpful :)

It seems that I cannot create a child object before saving the parent. I created a test project that matches the one displayed on this page. 
So to sum up, the "add another c"-button has no functionality before saving B

Is there a way to achieve this?

This is a link to the SO post I made regarding this issue, just in case that´s helpful.
http://stackoverflow.com/questions/31850292/django-grappelli-nested-inlines-cannot-create-new-nested-lines-after-initial-loa

**Comment by allanjamesvestal** [comment]
Thanks for using this plugin! Glad it's helpful for you.

If I understand your issue correctly, it may be problematic by design based on Django's own internals.

For example, if I create an instance of "model C", but it isn't tied to "model A" at all (through the link "model B" has to "model A"), how would Django know to display that "C" instance on the correct "A" instance's edit page?

I've found that what usually works best in such cases is creating a bare-bones instance of "B" that will make all the model-to-model relationships work as expected, but then having some logic that forces users to add more description to that "B" instance before any of the "B" or "C" data is published.

Does that sound doable in your case? Let me know and I'd be happy to help you get your setup working as intended.

**Comment by allanjamesvestal** [comment]
Edit: After reading your SO question, I realize there's a chance you were talking more about rapid succession — saying that you're trying to save a valid "B" instance at the same time as your first "C" instance, but that you can't create both on the same "save" click.

If that's the case, let me know that, too. I suspect the `extra = 0` setting in the admin for "model B" might be the culprit, but would have to double-check for myself to make sure my library isn't behaving in unexpected ways.

**Comment by RonnieHemmingsen** [comment]
Hi,
Thank you so much for responding.

Like you say, I am attempting to save the "B" instance at the same time as the first "C".
Please refer to the image below for my original attempt
<img width="1412" alt="django_issue_annotated" src="https://cloud.githubusercontent.com/assets/5370524/9132099/47b88308-3cf1-11e5-838c-fb10dbee9a2d.png">

If i remove the `extra = 0` I start out with 3 premade "B"', within those I can create nested "C"' without problems. If I use the "Add another b"-button, I am not able to create a new "C"-within that one. 
Please see the image below:
![django_nested_no_extra_zero_annotated](https://cloud.githubusercontent.com/assets/5370524/9132360/3a81b18a-3cf3-11e5-82d9-8181fb376c86.png)

I hope this is helpful, please let me know if you need anything else from me?
And thank you again :)
